### PR TITLE
Add Trusted Path Execution

### PR DESCRIPTION
**Pull request by nmatt0**
This patch was modified from Grsecurity's Trusted Path Execution feature

Implements the concept described here: http://phrack.org/issues/52/6.html#article

Signed-off-by: Matt Brown <matt@nmatt.com>

### CODE REVIEW

**Comment by nmatt0** [comment]
Got the request for this feature here:
https://wiki.gentoo.org/wiki/Talk:Hardened_Kernel#Trusted_Path_Execution_.28TPE.29

**Comment by sempervictus** [comment]
@nmatt0: Thanks for porting this functionality. Just out of curiosity, why a separate implementation from the tpe-lkm which seems to implement a number of other features from grsec? Are there security concerns around the ftrace imlementation, or just for readability and ease of adoption? Lastly, should
```
if (!security_tpe || !security_tpe_all)
```
be an OR, or actually an AND?

**Comment by nmatt0** [comment]
@sempervictus I had not seen tpe-lkm so I will have to look into that and see if I can expand on my current TPE. My initial opinion is that 

I regards to some of the logic in my TPE patch, I really need to revise some of that logic since I removed all of grsecurities ifdef's in exchange for using the variables `security_tpe`, etc everywhere. You are probably correct that should be an AND.

I am closing this PR in order to improve it. Work will be taking place in my dev branch at: https://github.com/nmatt0/linux-hardened/tree/nmatt-dev

**Comment by cormander** [comment]
Food for thought - ftrace is used because of code injection by and out-of-tree module. Building something in-tree shouldn't need to use that. I noticed that LSM may have become somewhat stackable with recent kernels, that's probably the best first approach here.

**Pull request closed without merging**
